- src/components/Avatar.tsx
- src/components/Quote.tsx
In the Quote component was broken position of avatar.
In the Avarat component I've added style:
```
justify-self: end;
```
> Quote: fixes position of avatar

- docs/getting-started/install.mdx
- docs/getting-started/integrate/browser.mdx
- docs/getting-started/integrate/index.mdx
- docs/getting-started/integrate/node.mdx
- docs/getting-started/mocks/graphql-api.mdx
- docs/getting-started/mocks/index.mdx
- docs/getting-started/mocks/rest-api.mdx
- docs/snippets/public-dir.mdx
- src/templates/docs/components/PageCollaborators.tsx
Current "Getting started" docs suggest a file structure that would lead to `setupWorker` being called in the NodeJS process. Overall setup is not something that should be recommended.
> Updates "Getting started" docs to reflect API changes

- gatsby-node.js
- src/templates/docs/components/EditOnGitHub.tsx
> Fixes a broken "Edit on GitHub" link

- docs/api/request/index.mdx
- docs/recipes/cookies.mdx
- Documents https://github.com/mswjs/msw/pull/261
> Docs: Adds "req.cookies" type and usage

- src/components/FullUsageExample.tsx
> Fix TS example typing on homepage

- src/components/ExampleItem.tsx
- src/images/logos/angular.svg
- src/pages/examples.tsx
- Successor to https://github.com/mswjs/examples/pull/28
> Adds Angular REST API example

- docs/recipes/request-assertions.mdx
- src/components/mdx/Hint.tsx
- src/theme.ts
- Originated from https://github.com/mswjs/examples/issues/30#event-3655533970
- Suggested in https://github.com/mswjs/msw/issues/339
> Docs: Adds the "Request assertions" recipe

- docs/basics/response-transformer.mdx
Just fix a mistyping in resolve word.
> Fix mistyping

- docs/getting-started/integrate/browser.mdx
- Originated from https://github.com/mswjs/mswjs.io/issues/54
> Docs (Getting started > Integrate): Removes the "webpack" alternative integration

- docs/getting-started/integrate/browser.mdx
> Docs (Integrate > Browser): Adds Service Worker reference for beginners

- docs/getting-started/install.mdx
- docs/getting-started/integrate/browser.mdx
Regarding the issue https://github.com/mswjs/msw/issues/354
I have added a note in the setup
> docs: add note using CRA

- docs/api/graphql/index.mdx
- docs/api/graphql/link.mdx
- docs/api/graphql/mutation.mdx
- docs/api/graphql/operation.mdx
- docs/api/graphql/query.mdx
- src/components/mdx/PageLink.tsx
- Adds `graphql.operation` docs
- Improves the GraphQL section of the API
- Closes #77
> Adds "graphql.operation" docs

- docs/recipes/custom-request-handler.mdx
- Closes https://github.com/mswjs/msw/issues/290
> Docs (Recipes): Adds a "Custom request handler" recipe

- docs/faq.mdx
> Fixes query parameters ref

- docs/faq.mdx
- Originates from https://github.com/mswjs/msw/issues/251#issuecomment-720309190
> Docs (FAQ): Adds notice about cache invalidation (react-query, swr)

- docs/index.mdx
- src/components/CarbonAds.tsx
- src/components/carbon-ads.css
- src/templates/docs/DocsLayout.tsx
- src/templates/docs/singlePage.tsx
These changes add Carbon ads to the documentation.
> Adds Carbon ads to the documentation

- docs/basics/request-matching.mdx
- src/components/CopyTextButton.tsx
- src/components/Footer.tsx
- src/components/mdx/Code.tsx
- src/components/mdx/PathMatchPreview.tsx
- src/hooks/useIsomorphicLocation.ts
- src/pages/index.tsx
- src/pages/repl.tsx
Adds the aforementioned page so it's easier to test URL matching and share the state with others.
> Adds "Path matching REPL" page

- docs/recipes/deferred-mounting.mdx
Fixes a typo in Deferred mounting example code.
> Fixed a typo in deferred mounting documentation

- docs/recipes/custom-transformer.mdx
Adds documentation for https://github.com/mswjs/msw/pull/441
cc @marcosvega91, feel free to comment if I missed something
> docs: add custom transformer

- docs/api/setup-worker/reset-handlers.mdx
- docs/api/setup-worker/restore-handlers.mdx
Update code examples to be consistent with example from https://mswjs.io/docs/api/setup-worker/use#examples
> docs: update runtime code examples

- docs/api/setup-server/print-handlers.mdx
- docs/api/setup-worker/print-handlers.mdx
- Implemented in https://github.com/mswjs/msw/pull/450
> Adds "printHandlers" method on setupWorker/setupServer

- docs/api/graphql/operation.mdx
Based on the conversation we had in [this issue](https://github.com/mswjs/msw/issues/428) I want to improve the `graphql.operation` method example for future reference.
> Improve operation example

- docs/recipes/custom-transformer.mdx
- https://github.com/mswjs/msw/pull/467
> Docs (Custom transformer): Adds async transformer example

- docs/index.mdx
Noticed a small typo while reading the docs, thought I might as well fix it
> Fixed a typo in the docs

- docs/basics/response-resolver.mdx
Noticed this incorrect example while implementing and threw me off.
> Update docs to have correct URLSearchParams

- docs/extensions/life-cycle-events/index.mdx
Documents new Life-cycle events feature.
> Adds "Life-cycle events" extensions page

- docs/faq.mdx
Regarding https://github.com/mswjs/msw/issues/569
_Description_
- update guideline on how to clear react-query cache
> feat(faqs): update react-query v3 guide

- README.md
- docs/cli/init.mdx
- docs/faq.mdx
- docs/getting-started/integrate/browser.mdx
- gatsby-config.js
- gatsby-node.js
- Documents https://github.com/mswjs/msw/issues/605 (https://github.com/mswjs/msw/pull/606)
> Docs: Mentions "msw.workerDirectory" for worker auto-updates

- docs/recipes/request-assertions.mdx
resolves https://github.com/mswjs/msw/issues/719
> Mention life-cycle API in Request assertions recipe

- docs/extensions/life-cycle-events/index.mdx
- Documents https://github.com/mswjs/msw/pull/868
> Rewrites the "Life-cycle events" page

- docs/snippets/public-dir.mdx
Add support for Vite to list of public directories
Docs: https://vitejs.dev/guide/assets.html\#the-public-directory
> docs: Vite Public Directory

- README.md
Uses the same logo in the README as on the website.
> fix: update logo in the readme

- docs/api/context/set.mdx
> Fix content-type typo

- docs/api/setup-worker/restore-handlers.mdx
> Fix restore-handlers typo

- docs/api/request/index.mdx
- docs/api/request/passthrough.mdx
- docs/basics/response-resolver.mdx
Documentation for `req.passthrough` (https://github.com/mswjs/msw/pull/1204).
> docs: add "req.passthrough" page

- docs/api/graphql/operation.mdx
- docs/api/request/index.mdx
- docs/basics/response-resolver.mdx
- docs/recipes/mocking-error-responses.mdx
- src/components/FullUsageExample.tsx
- Follow up to https://github.com/mswjs/interceptors/pull/267
- Documents https://github.com/mswjs/msw/pull/1316
Documentation for https://github.com/mswjs/msw/issues/1302
> docs: mention request body methods, update reading request body

- docs/index.mdx
An A/B experiment to see if this can drive more conversion from the introduction page.
> docs: enables ads on the intro page

- src/components/FullUsageExample.tsx
refer to https://github.com/mswjs/mswjs.io/pull/234
Fix the incorrect data structure.
> docs: update incorrect data structure

- docs/index.mdx
Just a few small changes, feel free to discard them if you don't appreciate my pedantry. ;)
> Small grammar changes

- src/content/docs/basics/intercepting-requests.mdx
I guarantee this will be the smallest PR you see for today 😂 
Congrats on the launch, been looking forward to it 🚀
> Align code snippet to be consistent with terminology

- src/content/blog/introducing-msw-2.0.mdx
Just changes a few words here and there to be grammatically correct
> fix grammar in 2.0 announcement post

- src/content/docs/migrations/1.x-to-2.x.mdx
Documents the fix for https://github.com/mswjs/msw/issues/1786
> add jsdom export condition to migration guidelines

- src/content/docs/migrations/1.x-to-2.x.mdx
> fix mistype in Update 1.x-to-2.x.mdx

- src/pages/docs/[...slug].astro
Related to #264 and https://github.com/mswjs/msw/issues/1789
> show 1.x docs banner on all pages

- src/content/docs/integrations/browser.mdx
Seems like a typo. Thank you for your work.
> Update browser.mdx: regsitering → registering

- src/content/docs/api/setup-worker/index.mdx
> Update index.mdx - Fix typo

- src/content/docs/api/graphql.mdx
> Update graphql.mdx - Fix typo

- src/content/docs/best-practices/network-behavior-overrides.mdx
Fixed a typo in Network Behavior Overrides document
> Fix a typo

- src/content/docs/network-behavior/rest.mdx
> docs: update network-behavior/rest.mdx

- src/content/docs/migrations/1.x-to-2.x.mdx
> docs: update 1.x-to-2.x.mdx

- src/content/docs/concepts/request-handler.mdx
update comment in example code
> docs: update concepts/request-handler.mdx

- src/content/docs/best-practices/dynamic-mock-scenarios.mdx
> docs: update best-practices/dynamic-mock-scenarios.mdx

- src/content/docs/basics/mocking-responses.mdx
> docs: update basics/mocking-responses.mdx

- src/content/docs/api/http-response.mdx
fix small typo with best guess
> docs: update api/http-response.mdx

- src/content/docs/api/setup-worker/start.mdx
> docs: update api/setup-worker/start.mdx

- src/content/docs/api/setup-worker/index.mdx
fix small typo in call signature description
> docs: update setup-worker/index.mdx

- src/content/docs/api/setup-server/listen.mdx
> docs: update listen.mdx

- src/content/docs/api/setup-server/listen.mdx
> adds missing "bypass" option description

- src/content/docs/recipes/higher-order-resolver.mdx
- Closes https://github.com/mswjs/mswjs.io/discussions/307
> fix incomplete example in higher-order resolver

- src/components/react/info.tsx
- src/components/react/success.tsx
- src/components/react/warning.tsx
- src/content/docs/integrations/browser.mdx
- src/content/docs/integrations/node.mdx
- src/content/docs/integrations/react-native.mdx
Even incomplete, a React Native integration can be useful.
> add react native integration

- src/content/docs/api/graphql.mdx
- Documents https://github.com/mswjs/msw/pull/1853
> add "cookies" to graphql handler variables

- src/content/docs/api/setup-server/listen.mdx
> Small spelling fix

- src/content/docs/runbook.mdx
Adds the actual runbook to follow.
> docs: add debugging runbook

- src/content/docs/basics/mocking-responses.mdx
The next minor release of MSW will support throwing responses in response resolvers. Let's document that.
> document throwing responses

- src/content/docs/basics/intercepting-requests.mdx
- src/content/docs/basics/mocking-responses.mdx
- src/content/docs/getting-started.mdx
> link to using with ts on relevant pages

- src/content/docs/api/get-response.mdx
- src/content/docs/recipes/graphql-query-batching.mdx
Documents https://github.com/mswjs/msw/pull/1982
> add GraphQL batched queries recipe

- src/content/docs/comparison.mdx
> docs(comparison): fix typo

- src/content/docs/comparison.mdx
Finally add the implementation details of `page.route()` in Playwright.
> add page.route() implementation

- src/content/docs/api/setup-server/listen.mdx
> setupServer: handle request.url as a string

- src/content/docs/getting-started.mdx
- Closes https://github.com/mswjs/msw/issues/2142
> await fetch in getting started

- websites/source.mswjs.io/src/content/docs/api/from-open-api.mdx
> Update from-open-api.mdx to fix typo

- websites/mswjs.io/src/content/docs/shared/jest-missing-globals.mdx
Fixes issue faced by some users as reported https://github.com/mswjs/msw/issues/2286
> Make Request and Response configurable in Jest polyfills

- websites/mswjs.io/src/content/docs/basics/intercepting-requests.mdx
- Fixes https://github.com/mswjs/msw/pull/2425
> link to the correct `path-to-regexp` version

- websites/mswjs.io/src/content/docs/api/is-common-asset-request.mdx
- websites/mswjs.io/src/content/docs/api/setup-server/listen.mdx
- websites/mswjs.io/src/content/docs/api/setup-worker/start.mdx
Documents https://github.com/mswjs/msw/pull/2440
> add `isCommonAssetRequest` docs

- websites/mswjs.io/src/content/docs/api/http-response.mdx
- Addresses https://github.com/mswjs/mswjs.io/discussions/460
> add body+init example to `HttpResponse.json`

- websites/mswjs.io/src/content/docs/limitations.mdx
- websites/mswjs.io/src/content/docs/recipes/xmlhttprequest-progress-events.mdx
- Related to https://github.com/mswjs/msw/discussions/1937
- Related to https://github.com/mswjs/msw/issues/2549
> add xhr progress event limitation

- websites/mswjs.io/src/content/docs/http/intercepting-requests/query-parameters.mdx
- websites/mswjs.io/src/content/docs/http/mocking-responses/response-timing.mdx
- websites/mswjs.io/src/content/docs/http/mocking-responses/streaming.mdx
> Fix broken page links

- websites/mswjs.io/src/content/blog/enter-websockets.mdx
- websites/mswjs.io/src/content/blog/introducing-server-boundary.mdx
- websites/mswjs.io/src/content/blog/why-use-mock-service-worker.mdx
- websites/mswjs.io/src/content/docs/api/ws.mdx
- websites/mswjs.io/src/content/docs/graphql/intercepting-operations/index.mdx
- websites/mswjs.io/src/content/docs/graphql/mocking-responses/index.mdx
- websites/mswjs.io/src/content/docs/http/handling-requests.mdx
- websites/mswjs.io/src/content/docs/http/mocking-responses/polling.mdx
- websites/mswjs.io/src/content/docs/philosophy.mdx
- websites/mswjs.io/src/content/docs/recipes/using-local-https.mdx
- websites/mswjs.io/src/content/docs/websocket/client-events/client-to-server-forwarding.mdx
- websites/mswjs.io/src/content/docs/websocket/type-safety.mdx
- websites/mswjs.io/src/pages/index.astro
- websites/source.mswjs.io/src/content/docs/integrations/har.mdx
> chore: fix typos
