mswjs/mswjs.io

- src/components/Quote.tsx
- src/components/Section.tsx
- src/pages/index.tsx
- src/sections/Features.tsx
- src/sections/Highlights.tsx
in the Index component hr line has margin which was not needed.
in the Quote component spacing was bigger than in the other components.
In the mobile screen end quote was empty but did not hide.
Index component: deleted margin top.
in the Box around the Quote component fixes spacing to the 64px.
Quote: in the QuoteContainer made after quote `display: none` and from md screen `display: inline-block`
> Fixes spacing

- docs/api/setup-server/use.mdx
Looks like a tiny setupWorker got in accidentally.
> Fix typo in use() docs

- docs/getting-started/integrate/node.mdx
Closes #11
I used the phrase "request mocking server" here a couple times because just "server" felt ambiguous. Perhaps you'll have a better alternative.
> Docs: Adjusts "Getting Started" to include configuring the Node server

- docs/getting-started/integrate/node.mdx
Ensures that the test framework has been loaded and the before* and after* hooks are available.
When I run the code as in the example, I get an error: "ReferenceError: beforeAll is not defined". Switching the config entry from `setupFiles` to `setupFilesAfterEnv` fixed this issue for me.
It is possible that I was doing something wrong, and if so, please let me know!
> Updates jest.config.js to use setupFilesAfterEnv

- docs/getting-started/install.mdx
Avoid people installing `msw` as a `dependency`, but instead it should be installed as a `devDependency` .
As the definition of dependency, it's something that will be bundled and shipped to the application code (but `msw` doesn't meet that requirement).
- Updated install docs
> Updated install docs (install as dev dependency)

- docs/getting-started/integrate/node.mdx
- Mentions that for a direct usage in NodeJS (not as a part of any testing framework), one must always use absolute request URLs in request handlers.
- Surfaced from https://github.com/mswjs/msw/issues/263
> Docs (Node): Mentions required absolute request URL for NodeJS

- docs/snippets/public-dir.mdx
They were reversed.
see https://nextjs.org/docs/basic-features/static-file-serving and https://www.gatsbyjs.org/docs/static-folder/
> Fix Gatsby and Next.js public directories

- docs/api/request/index.mdx
@kettanaito 
I noticed the _query_ ppty was absent from the ts types.
I found a thread where you say it's been deprecated but found it in the docs
don't know if this is valid and if so if you want to phrase it like that (or no at all ;)
thanks
> Docs (Request): Removes deprecated "query", fixes "URL" type, adds "keepalive"

- docs/recipes/binary-response-type.mdx
- Adds a new "Binary response type" recipe to the documentation. That recipe illustrates how to respond with a local image.
- Documents https://github.com/mswjs/msw/issues/221 (https://github.com/mswjs/msw/pull/224)
> Docs: Adds "Binary response type" recipe

- docs/api/response/networkError.mdx
> Should be merged for the `0.20.0` release.
- Documents the `res.networkError()` method.
> Docs (Response): Adds the "networkError" method

- docs/getting-started/integrate/browser.mdx
In the documentation, there is a line which says:
"Import the `mocks.js` file conditionally following one of the examples below"
But `mocks.js` is never defined in the whole document page, and it supposed to be `browser.js` but wrongly addressed a different file (which did not exist)
> Wrong file name, it should be "browser.js"

- docs/recipes/binary-response-type.mdx
Extended the binary response recipe to add an example use case with `setupServer` in a node environment, following https://github.com/mswjs/msw/pull/318
> Added `setupServer` example to binary response recipe

- docs/api/graphql/index.mdx
- docs/api/graphql/link.mdx
- Adds `graphql.link()` API to the docs.
- Documents https://github.com/mswjs/msw/pull/319
> Docs (API: graphql): Adds "graphql.link" API

- docs/faq.mdx
Helps people better understand security aspects behind using the Service Worker API.
> Docs (FAQ): References Service Worker security page from Google

- docs/api/rest.mdx
small typo in the rest docs page
thanks!
> docs(): Fix typo namepsace -> namespace

- docs/basics/response-resolver.mdx
A required comma between function arguments was missing.
> Fix "Reusable resolver" code to be valid JS

- docs/snippets/public-dir.mdx
I'm not entirely sure if this is the best way to put it.
Do you think this is fine, or what could be improved?
For more info:
The public folder for an angular application is actually `./src/assets`. If a file is added to that directory, it well get served automatically. The "problem" is that the default behavior of MSW expects the `mockServerWorker.js` to be available under `/mockServerWorker.js`. If we put that file inside the assets, it's available under `/assets/mockServerWorker.js`. This would mean that we don't have to make a change to the angular compile step, but rather a change to the setup of MSW.
In the angular settings you can add more files (or directories) to be included in the public folder. This is the way that I'm currently using, and this is also how this is documented …
> docs: add angular public

- src/sections/Integration.tsx
Just a small typo in the integration section 🙂
Thank you!
> docs: fix typo Sercive -> Service

- docs/api/context/delay.mdx
Prevents confusion over what the "realistic" term refers on that page.
> Docs (delay): Elaborates on the "realistic" response time

- package.json
- yarn.lock
This PR upgrades node-match-path so the path match tool at the website will support underscores in path parameters.
> Upgrade node-match-path to 0.5.1

- docs/snippets/public-dir.mdx
Hi, I'm enjoying MSW in several React projects, and now I'm playing with Preact.
In projects created with [Preact CLI](https://preactjs.com/cli), any files in `src/static/` will be copied to `build/` directory.
https://github.com/preactjs/preact-cli/blob/v3.0.3/packages/cli/lib/lib/webpack/webpack-client-config.js#L99-L103
> docs: add Preact CLI's public directory

- docs/basics/request-handler.mdx
update link from `Path matching` to `Request matching`
> Docs: update link to Request matching

- docs/basics/request-matching.mdx
See title, just a single character change
> docs: just a small small typo, hases => hashes

- docs/basics/response-transformer.mdx
The current link for ctx, https://mswjs.io/docs/basics/response-resolver/context#standard-context, returns a 404. This PR replaces it with the actual context page.
> docs: Update broken link for ctx

- docs/recipes/response-patching.mdx
mention having to await the response to be converted from readableStream to JSON before being able to use it in the MSW mocked response
> fix(response patching): convert readableStream to JSON

- docs/faq.mdx
This is one of the most commonly asked questions, so it belongs to the FAQ page.
> Docs (FAQ): Explains why query parameters must be dropped

- docs/faq.mdx
As we started migration from the Apollo `MockedProvider` to MSW, one issue we ran into was the Apollo Client caching query results between tests. This is the solution that worked best for us, but I'm open to discuss alternatives.
Thanks for all of your incredible work on MSW! Our test suites (and engineers) are much happier after our migration.
> docs: Add cache reset example for Apollo Client

- docs/recipes/query-parameters.mdx
As title, replace the typo "propery" with "property" in query-parameter page.
See #113
> Fix typo "propery" in query-parameters page

- docs/getting-started/integrate/node.mdx
As the documentation says, it's better to use a relative path to reference `jest.setup.js` file.
Otherwise, it often cannot be found.
ref: https://jestjs.io/docs/en/configuration.html#setupfilesafterenv-array
> Update relative path for jest.setup.js file

- docs/getting-started/integrate/browser.mdx
Add an example to deal with `homepage` property.
> docs: Add `homepage` property example to browser.mdx

- docs/recipes/usage-with-cdn.mdx
With the release of msw 0.25.0 and the availability of an iife bundle, executing msw from a CDN works! 
This is an update to the documentation to reflect the change.
> Update CDN example

- docs/extensions/life-cycle-events/index.mdx
The `Map` variable name in the `Tracking a request` documentation section is inconsistent and misleading
> Fix Life-cycle events documentation variable name

- docs/api/graphql/query.mdx
- docs/getting-started/mocks/graphql-api.mdx
Not sure what’s the actual problem (Apollo?) but probably worth documenting: I had undefined `data` without any errors until I added `__typename` everywhere.
> docs: Add warning about __typename

- docs/recipes/debugging-uncaught-requests.mdx
Provides a recipe for one of the most common issues.
> Docs: Adds "Debugging uncaught requests" recipe

- docs/getting-started/mocks/rest-api.mdx
This example has a TS error. I fixed it.
> Argument of type 'boolean' is not assignable to parameter of type 'string'.ts(2345)
> docs(rest-api): fix ts error

- docs/recipes/binary-response-type.mdx
Add an exclamation mark before `url-loader` to disable other binary file loaders.
https://webpack.js.org/concepts/loaders/#inline
> Add exclamation mark before url-loader

- docs/api/response/index.mdx
While using msw, I noticed that `res(ctx.status(200))` does not have to be passed explicitly, instead if no `ctx.status()` is provided, it defaults to 200. 
When I was first starting out, I wasn't sure if 200 indeed was the default, so I tried looking it up in the docs and I couldn't find it.
If 200 indeed is the default `ctx.status()` value, then I think, it would be helpful if it was clearly outlined somewhere in the docs
> docs: add default response status value

- docs/api/setup-server/index.mdx
The link to `setupWorker` on the `setupServer` page was broken.
> Fix link from setup-server to setup-worker

- docs/api/context/set.mdx
When setting 'Content-Length' header as a number, you get an error using Typescript. Header value should be a strings or array of strings.
Argument of type '[{ 'Content-Type': string; 'Content-Length': number; }]' is not assignable to parameter of type '[string, string] | [Record<string, string | string[]>]'.
Type '[{ 'Content-Type': string; 'Content-Length': number; }]' is not assignable to type '[Record<string, string | string[]>]'.
Type '{ 'Content-Type': string; 'Content-Length': number; }' is not assignable to type 'Record<string, string | string[]>'.
Property ''Content-Length'' is incompatible with index signature.
Type 'number' is not assignable to type 'string | string[]'.ts(2345)
> 'Content-Length' value should be a string

- docs/recipes/using-local-https.mdx
We should recommend to our users how to approach worker registration errors when using MSW with a local HTTPS server.
> Adds "Using local HTTPS" recipe

- docs/api/setup-server/listen.mdx
The default value has been changed in [this pull request](https://github.com/mswjs/msw/pull/703).
> Fix the default value of onUnhandledRequest

- docs/extensions/life-cycle-events/index.mdx
`req.url` looks like it's a url object, but if we pass a url object it ends up failing here:
https://github.com/mswjs/msw/blob/87972dcf24783fb1988b4944b2489ab8194a3e29/src/utils/url/getAbsoluteUrl.ts#L6
> Convert req.url to string before passing to `matchRequestUrl`

- docs/api/context/extensions.mdx
**Description**
Adding the docs in relation to the recent pull request [981](https://github.com/mswjs/msw/pull/981).
**Comments**
- Left the order the same as `api/context/data.mdx` given it should follow data in the layout.
- Do we want another example of `extensions` being used as a stand-alone or is that pretty self-explanatory. I went with the latter
> Extensions Docs

- docs/recipes/using-local-https.mdx
Found a tiny typo, happy to help making these docs even nicer 🙂 
`vulnurabilities` -> `vulnerabilities`
> fix typo in `using-local-https.mdx`

- docs/extensions/life-cycle-events/index.mdx
`matchRequestUrl` returns a [`Match` object](https://github.com/mswjs/msw/blob/2e7ecd87e5568c6e59a408e812535f088498e437/src/utils/matching/matchRequestUrl.ts#L8-L11), and not a boolean.
Therefore in this example `matchesUrl` was always truthy, even if the request url was not matching.
This fix update the example to use the `matches` property from the `Match` object instead.
> docs: fix error in `waitForRequest` example

- docs/extensions/life-cycle-events/index.mdx
`waitForRequest` always returns `unknown ` in TypeScript.
```ts
const pendingRequest = waitForRequest('POST', '/login');
const request = await pendingRequest;
// Object is of type 'unknown'.ts(2571)
expect(request.body).toEqual({
email: 'user@example.com',
password: 'super+secret123',
})
```
So, i want to improve the return type of waitForRequest  in the docs.
> docs: Improve the return type of waitForRequest

- docs/cli/init.mdx
- docs/getting-started/install.mdx
- docs/getting-started/integrate/browser.mdx
- docs/getting-started/integrate/node.mdx
- docs/getting-started/mocks/index.mdx
- docs/recipes/debugging-uncaught-requests.mdx
- docs/recipes/usage-with-cdn.mdx
Remove the leading dollar sign in code blocks to fix errors in the terminal when copying the command to the clipboard
> docs: Leading Dollar Sign

- docs/faq.mdx
Looks like the SWR API changed in this regard. There's no `cache` export available anymore.
> docs: update SWR cache clearing instruction

- docs/snippets/public-dir.mdx
I've just came across this page in the way trying msw to my SvelteKIt app and found it isn't there yet. Hopefully this helps.
cite: https://kit.svelte.dev/docs/configuration
> chore: Add SvelteKit to the public directory table

- docs/getting-started/integrate/browser.mdx
Replaces `windows` with `window` in the "Browser - Getting Started" page.
> docs: fix typo

- docs/faq.mdx
This revises the FAQ to describe that React Native is largely supported, as discussed in [this issue](https://github.com/mswjs/msw/issues/203#issuecomment-1278868131).
@kettanaito I see that you have an [unmerged branch](https://github.com/mswjs/mswjs.io/tree/docs/react-native) `docs/react-native`. Is that up to date? Can it be merged soon too?
> Update FAQ on React Native support

- docs/api/setup-server/reset-handlers.mdx
Fixes a typo in `reset-handlers.mdx`.
> docs: fix a typo in reset-handlers.mdx

- src/content/docs/api/graphql.mdx
- src/content/docs/network-behavior/graphql.mdx
- src/content/docs/recipes/mock-graphql-schema.mdx
There were two typos, one in a heading (plus two links linking to it) and another mis-spelled "drop".
> docs: fix two typos

- src/content/docs/migrations/1.x-to-2.x.mdx
Awesome work and congrats on the 2.0 release! Had to read and see if my whines somehow made it onto the docs haha.
Just found this wording which I assume was meant to infer a later version of node, not an **older** version. I assume you don't want people moving to Node v8 to run msw2.
> fix incorrect wording on node.js requirement

- src/content/docs/migrations/1.x-to-2.x.mdx
- `TextDecoder` was being used as both `TextDecoder` _and_ `TextEncoder`
- "Respose" -> "Response" (also covered in #274, looks like we were doing this at the same time...)
> Fix typos in migration guide

- src/content/docs/api/http-response.mdx
To prevent confusion whether those values are allowed. They are.
> add null and undefined to HttpResponse body argument type

- src/content/docs/runbook.mdx
Update runbook to discuss selective faking of fake timers in jest
> add jest.useFakeTimers() to the runbook

- src/content/docs/faq.mdx
- src/content/docs/migrations/1.x-to-2.x.mdx
- src/content/docs/shared/jest-missing-globals.mdx
We list different suggestions in FAQ and 1.x -> 2.x migration guidelines regarding `Request` is not defined in Jest. Unify those.
> reuse jest missing globals solution

- src/content/docs/shared/jest-missing-globals.mdx
When using jsdom this value conflicts with jsdom's own `Blob` and `File`, importing and specifying here that we want the global value to be the one from node avoids that.
This was reproducible if you tried to do something like this (assuming you'd copy-pasted the snippet I've edited across to your jest test setup):
```js
const data = new FormData(); // this FormData is the nodejs one
const myFile = new File(['some,file,contents', 'filename.csv', { type: 'text/csv' }) // this File is the jsdom one
data.append('fileInput', myFile, myFile.name)
// throws with:
// TypeError: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'
```
In addition/to verify:
Before:
```js
const myFile = new File(['some,file,contents', 'filename.csv', { type: 'text/csv' })
myFile instanceof …
```
> Update jest-missing-globals.mdx to use nodejs File

- src/content/docs/best-practices/custom-request-predicate.mdx
First of all: Thank you for the great library :heart:
This PR contains a small fix for the examples in `custom-request-predicate.mdx`. Since `args` is in the current version a list deconstructing `request` via `const { request } = args` does not work. Since a resolver has only one argument in the current type definitions, it should be okay to change the function in this was.
There would be another fix by writing `const { request } = args[0]`.
> docs: Change argument list to a single argument in `custom-request-predicate.mdx`

- src/content/docs/api/setup-server/reset-handlers.mdx
- src/content/docs/api/setup-server/use.mdx
Fix issue #302 
Links from https://mswjs.io/docs/api/setup-server/use page and https://mswjs.io/docs/api/setup-server/reset-handlers page to "Network Behavior Overrides" were broken.
Replaced with the correct link
https://mswjs.io/docs/best-practices/network-behavior-overrides/
> fix: broken links to page 'network-behavior-overrides' #302

- src/content/docs/recipes/responding-with-binary.mdx
I found that the second argument of HttpResponse.arrayBuffer requires a headers key, similar to the Browser item.
> fix responding with binary usage

- src/content/blog/why-use-mock-service-worker.mdx
Great read, noticed this while going through it.
> Typo fix in why-use-mock-service-worker.mdx

- src/components/react/docsSidebarLinks.tsx
- src/components/react/footer.tsx
- src/layouts/DocsPage.astro
The TOC sidebar becomes unscrollable on pages with a lot of headings.
> fix toc sidebar scroll

- src/content/docs/api/get-response.mdx
The [Response: json()](https://developer.mozilla.org/en-US/docs/Web/API/Response/json) method returns a `Promise`, so it should add `await` in this example.
> fix: add missing `await` keyword

- src/content/docs/basics/intercepting-requests.mdx
According to `getAbsoluteUrl` function [implementation](https://github.com/mswjs/msw/blob/main/src/core/utils/url/getAbsoluteUrl.ts#L20), `document.baseURI` should be polyfilled, not `window.location`.
> mention "document.baseURI" polyfill in relative URLs with Node.js

- src/content/docs/best-practices/typescript.mdx
The example code of [withDelay](https://mswjs.io/docs/best-practices/typescript#higher-order-response-resolvers) seems to be cause type error due to the lack of type parameter of `HttpResponseResolver`.
This patch may not the best, but it works collectly.
> fix: add missing type parameter to `withDelay` example

- src/content/docs/api/get-response.mdx
The current `getResponse` example code works only browser due to that the [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request) constructor generate a URL from the URI like `/user`.
But it don't act well non-browser environment like node because of it requires URL.
We should show better for both environment.
I picked it from here.
https://github.com/mswjs/msw/blob/ad8ebac0c6b3c1dd66bf275b8c9d06370607e9c6/src/core/getResponse.test.ts#L41-L44
> fix: valid URI and URL for `getResponse` example to work every environment

- src/content/docs/faq.mdx
This is based on the guidance we now give in our own documentation ([source](https://www.apollographql.com/docs/react/development-testing/schema-driven-testing/#should-i-share-a-single-apolloclient-instance-between-tests)). I started by basically quoting the section wholesale but would be happy to adjust the language as needed :)
> faq: update apollo client cache suggestions

- websites/mswjs.io/src/content/docs/api/delay.mdx
Added missing `controller` parameter to the example of controlling precise delay timing when mocking response streams.
> fix: added missing `controller` parameter

- websites/mswjs.io/src/content/docs/best-practices/index.mdx
- websites/mswjs.io/src/content/docs/best-practices/managing-the-worker.mdx
- websites/mswjs.io/src/content/docs/cli/init.mdx
- websites/mswjs.io/src/content/docs/integrations/browser.mdx
- Mention that we support multiple `msw.workerDirectory` values.
- Cross-reference browser integration, managing the worker, and the CLI command.
> add "Managing the worker" best practice

- websites/mswjs.io/src/components/DocsV1Banner.astro
- websites/mswjs.io/src/layouts/BaseLayout.astro
- websites/mswjs.io/src/pages/docs/[...slug].astro
- websites/mswjs.io/src/pages/docs/index.astro
While working on #397, I seem to have lost the v1 docs banner. This re-adds it.
> revert v1 docs banner

- websites/mswjs.io/astro.config.mjs
- websites/mswjs.io/package.json
I noticed that `Edit this page on GitHub` links were broken when I was about to suggest a small update to a link on the [`resetHandlers` page](https://mswjs.io/docs/api/setup-server/reset-handlers/) (will open a separate PR).
Since this was recently refactored it was easy to see what was missing here - and the `repository.url` also needed a trailing `/` :)
> fix: Edit this page on GitHub links on mswjs.io

- websites/mswjs.io/src/content/docs/migrations/1.x-to-2.x.mdx
- websites/mswjs.io/src/content/docs/shared/jest-missing-globals.mdx
Finally recommends https://github.com/mswjs/jest-fixed-jsdom instead of manual patches.
> Recommend `jest-fixed-jsdom` for jest

- websites/mswjs.io/src/content/docs/recipes/graphql-query-batching.mdx
- variable name
- argument for `getResponse`
> fix: graphql query batching example code

- websites/mswjs.io/src/content/docs/basics/handling-websocket-events.mdx
This PR fixes two small typos for `broadcastException`.
> Fix API typo (`broadcastException`)

- websites/mswjs.io/public/fonts/inter/inter.css
Safari was not able to properly render fonts that had a different font weight than `400`.  This is now fixed, and Safari can render the Inter font the same as the other browser.
Safari needs an explicit mapping for which font weight belong to which file. The solution was to widen the font-face rule for the variable font so it includes all font weights from 100 to 900.
I've added some before and after pictures. Left is before and right is after.
<br />
> fix font rendering for Safari

- websites/shared/components/SocialLinksList.astro
The footer Discord link redirects to an incorrect page.
This PR fixes the typo, redirects to `https://kettanaito.com/discord`
> fix: footer dead link

- websites/mswjs.io/src/content/docs/http/mocking-responses/response-patching.mdx
This fixes the code snippet in the response-patching page by matching the usage of `bypass` found elsewhere https://mswjs.io/docs/api/bypass/
> fix unwrapped bypass function in response-patching.mdx

- websites/mswjs.io/src/content/docs/http/mocking-responses/network-errors.mdx
Minor correction to the documentation in `network-errors.mdx`. The change fixes a typo in the word "instance"
> docs: Update network-errors.mdx
